/*
 * Name: Dattran
 * Date:
 * Project's name: Library Manage System
 * Teacher's name:
 * Class name: VUW-IT 15
 * Name of anyone who help you:
 * Brief Discription: system for managing lib system
 */
package users_gui;

import static main_gui.Login.USERNAME;
import static main_controller.connectDataP.conn;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import users_controller.UserUnregister_c;

/**
 *
 * @author dattr
 */
public class UserUnregister extends javax.swing.JPanel {

    /**
     * Creates new form UserRegister
     */
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement ptmt = null;
    DefaultTableModel model ;
    UserUnregister_c urc = new UserUnregister_c();
    public UserUnregister() {
        initComponents();
        model = (DefaultTableModel) Table.getModel();
    }

    public void start(){
        Start.setText("register Book");
    }
    
    public void clearTable(){
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }
    
    public void View(){
        clearTable();
        try{
            stmt = conn.createStatement();
            
            rs = stmt.executeQuery("select * from registerbook1 where username = '"+USERNAME+"'");
            while (rs.next()) {
                /// hien thi tren table
                model.addRow(new Object[]{rs.getString(2)}); 
            }
        }catch(Exception ex){}
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Start = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        unregisterButton = new javax.swing.JButton();

        Start.setText("jLabel1");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "book name"
            }
        ));
        jScrollPane1.setViewportView(Table);

        unregisterButton.setText("unregister");
        unregisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unregisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Start))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(unregisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(unregisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Start))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void unregisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unregisterButtonActionPerformed
        // TODO add your handling code here:
        try{
            int index  = Table.getSelectedRow();
            String bookname = (String) Table.getValueAt(index, 0);
            if(urc.fixRemain(USERNAME)){
                urc.delete(USERNAME, bookname);
                urc.fixStatus("valid", bookname);
                View();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "please choose or register one book");
        }
    }//GEN-LAST:event_unregisterButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Start;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton unregisterButton;
    // End of variables declaration//GEN-END:variables
}
