/*
 * Name: Nguyễn Thế Đại
 * Date:
 * Project's name: Library Manage System
 * Teacher's name:
 * Class name: VUW-IT 15
 * Name of anyone who help you:
 * Brief Discription: system for managing lib system
 */
package librarian_gui;

/**
 *
 * @author Nguyễn Thế Đại
 */
public class BookManage extends javax.swing.JPanel {

    /**
     * Creates new form BookManage
     */
    BookManage1 bm1 = new BookManage1();
    BookManage2 bm2 = new BookManage2();
    public BookManage() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addbookButton = new javax.swing.JButton();
        PanelMain = new javax.swing.JPanel();
        Start = new javax.swing.JLabel();
        bookmanageButton = new javax.swing.JButton();

        addbookButton.setText("add book");
        addbookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Start.setText("jLabel1");

        bookmanageButton.setText("book manage");
        bookmanageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookmanageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Start)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bookmanageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(addbookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(bookmanageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(addbookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(389, 389, 389)
                .addComponent(Start)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void start(){
        Start.setText("book manage");
    }
    
    private void bookmanageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookmanageButtonActionPerformed
        // TODO add your handling code here:
        try{
            PanelMain.removeAll();
        }catch(Exception ex){}
        bm1.setBounds(0, 0, 605, 555);
        bm1.clearTable();
        bm1.View();
        PanelMain.add(bm1);
        PanelMain.repaint();
        bm1.start();
    }//GEN-LAST:event_bookmanageButtonActionPerformed

    private void addbookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookButtonActionPerformed
        // TODO add your handling code here:
        try{
            PanelMain.removeAll();
        }catch(Exception ex){}
        
        bm2.setBounds(0, 0, 605, 555);
        PanelMain.add(bm2);
        PanelMain.repaint();
        bm2.start();
    }//GEN-LAST:event_addbookButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JLabel Start;
    private javax.swing.JButton addbookButton;
    private javax.swing.JButton bookmanageButton;
    // End of variables declaration//GEN-END:variables
}
