/*
 * Name: Lương Cao Đức
 * Date:
 * Project's name: Library Manage System
 * Teacher's name:
 * Class name: VUW-IT 15
 * Name of anyone who help you:
 * Brief Discription: system for managing lib system
 */
package librarian_gui;

/**
 *
 * @author Lương Cao Đức
 */
public class BorrowManage extends javax.swing.JPanel {
    //605,520
    /**
     * Creates new form BorrowManage
     */
    BorrowManage1 bm1 = new BorrowManage1();
    BorrowManage2 bm2 = new BorrowManage2();
    BorrowManage3 bm3 = new BorrowManage3();
    public BorrowManage() {
        initComponents();
    }
    public void start(){
        Start.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Start = new javax.swing.JLabel();
        PanelMain = new javax.swing.JPanel();
        returnlistButton = new javax.swing.JButton();
        returnlistbutton = new javax.swing.JButton();
        borrowlistButton = new javax.swing.JButton();

        Start.setText("jLabel1");

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        returnlistButton.setText("return list");
        returnlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnlistButtonActionPerformed(evt);
            }
        });

        returnlistbutton.setText("borrow list");
        returnlistbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnlistbuttonActionPerformed(evt);
            }
        });

        borrowlistButton.setText("register list");
        borrowlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowlistButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Start))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(borrowlistButton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(returnlistbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnlistButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(borrowlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnlistbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Start))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void borrowlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowlistButtonActionPerformed
        // TODO add your handling code here:
        try{
            PanelMain.removeAll();
        }catch(Exception ex){}
        
        bm1.setBounds(0, 0, 605, 520);
        bm1.View();
        PanelMain.add(bm1);
        PanelMain.repaint();
        bm1.start();
    }//GEN-LAST:event_borrowlistButtonActionPerformed
    // sau ông design phải chủ động tính toán @@
    private void returnlistbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnlistbuttonActionPerformed
        // TODO add your handling code here:
        try{
            PanelMain.removeAll();
        }catch(Exception ex){}
        
        bm2.setBounds(0, 0, 605, 520);
        bm2.View();
        PanelMain.add(bm2);
        PanelMain.repaint();
        bm2.start();
    }//GEN-LAST:event_returnlistbuttonActionPerformed

    private void returnlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnlistButtonActionPerformed
        // TODO add your handling code here:
        try{
            PanelMain.removeAll();
        }catch(Exception ex){}
        
        bm3.setBounds(0, 0, 605, 520);
        bm3.View();
        PanelMain.add(bm3);
        PanelMain.repaint();
        bm3.start();
    }//GEN-LAST:event_returnlistButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JLabel Start;
    private javax.swing.JButton borrowlistButton;
    private javax.swing.JButton returnlistButton;
    private javax.swing.JButton returnlistbutton;
    // End of variables declaration//GEN-END:variables
}
